### ISSUE TITLE
Could you give me a KT on this? Graphql especially? 

### ISSUE THREAD

**Issue by gdad-s-river** [jck-d-rpr/react-graphql-relay#1]

**Comment by jck-d-rpr** [comment]
I am myself new to grapql and relay. For this I was just following a [course](https://app.pluralsight.com/library/courses/react-apps-with-relay-graphql-flux/table-of-contents) on pluralsight.

For graphql:
First take a look at this [video](https://www.youtube.com/watch?v=Wq02BNrN1dU) introducing GrapQL 
Then go through the readme [here](https://github.com/facebook/graphql)
Then play around with with this awesome [app](http://graphql-swapi.parseapp.com/)

Then depending on what you are using on the server side search for an implementation of graphql in that programming language. Facebook provides a reference implementation in javascript and I have come across one in java.

You can use it without relay and react but these three are just awesome together.

**Comment by gdad-s-river** [comment]
Thanks bhai! happy holi!

**Comment by jck-d-rpr** [comment]
Also take a look at this [link](https://learngraphql.com/)

**Comment by gdad-s-river** [comment]
Thanks boss.
